### PR TITLE
#112/loading favourites

### LINKED ISSUE #112: Handle `loading` for `FavouritesPage.tsx` 🛄
### Description of the Bug

When the user visits `FavourtesPage` we see the message that says "no favourites saved" for a second while the user's actual favourites are being fetched

### What should happen instead

We should see a 'loading' message instead

### Steps to reproduce this bug

1. log in with a user that has no favourites saved
2. visit the 'favourites' page

### What could we do to solve this bug?

A simple local state tracking a boolean value to say if the information is loading could be lazily initialised as `true` and updated at the end of the fetch operation, allowing us to display a 'loading' message until data has been made available or the fetch has failed.

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by camelPhonso**
# Description

**Closes #112**

Creates a new higher order component that wraps any children given to it with the logic to handle a loading state.

I've applied this new component to both the `Favourites` and the `Explore` page as they both handle similar loading of a lot of data. This component flashes the logo in assets while we load because I thought that would be a more personalised look than just adding a spinner - but that's very much under question I think.

### Files changed

- `components/WithLoading/` - new component plus styling
- `FavouritesPage.tsx` and `ExplorePage.tsx` - import the new `WithLoading` component and wrap the elements displaying fetched data in it

### UI changes

The pages look exactly the same, but if you throttle the app you'll see the arebyte logo flashing for a few seconds before the data is loaded

### Changes to Documentation

n/a

# Tests

n/a - no changes to the logic in the code

### CODE REVIEW

File: src/components/WithLoading/WithLoading.tsx [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ */
+export default function WithLoading({
+  children,
+  isLoading
+}: {
+  children: JSX.Element
+  isLoading: boolean
+}) {
+  if (isLoading)
+    return <img className="with-loading__loading" src={logo} />
```
Comment (nichgalzin) [inline src/components/WithLoading/WithLoading.tsx]: As we discussed, lets wrap this in a div with flex center in whatever layout it's in.

**Review by nichgalzin — CHANGES_REQUESTED** [review]

File: src/components/WithLoading/WithLoading.tsx (hunk 1 above)
Comment (camelPhonso) [reply src/components/WithLoading/WithLoading.tsx]: schön gut 👌 

I've pushed this edit in a new commit

**Review by nichgalzin — APPROVED** [review]
Great stuff
