### PR TITLE
139/fav button fix

### LINKED ISSUE #139: Favourite button styling issue and log out state
### Description of the Bug

- When you add a popup to your favourites it now breaks the styling and the content wraps
- When the user is logged out the button should somehow communicate with the user that they need to log in.

[Image](https://github.com/user-attachments/assets/070a93a9-51f6-418c-9a0c-f7edb87baa66)

### What should happen instead

n/a

### Steps to reproduce this bug

n/a

### What could we do to solve this bug?

_No response_

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by nichgalzin**
# Description

**Closes #139 **  
Include here a short description of what behaviour this Pull Request introduces.
Outline any new dependencies introduced.

This pull request includes several changes to the `ManageFavouritesButton` component and a small CSS adjustment in the `PopupInfo` component.

Improvements to `ManageFavouritesButton` component:

* Added a new state `hasUserSession` to track if a user session exists. (`src/components/popup-components/ManageFavouritesButton/ManageFavouritesButton.tsx`)
* Updated the logic to check for a user session and set the `hasUserSession` state accordingly. (`src/components/popup-components/ManageFavouritesButton/ManageFavouritesButton.tsx`)
* Updated the component rendering to conditionally display the button controls only if a user session exists. (`src/components/popup-components/ManageFavouritesButton/ManageFavouritesButton.tsx`)

CSS adjustment:

* Increased the width of buttons in the `PopupInfo` component from 250px to 275px. (`src/components/popup-components/PopupInfo/PopupInfo.css`)

### UI changes

Screenshot 2024-11-15 at 11 27 30

Screenshot 2024-11-15 at 11 29 35

### CODE REVIEW

File: src/components/popup-components/ManageFavouritesButton/ManageFavouritesButton.tsx [hunk 1]
```diff
@@ -31,7 +37,8 @@ const ManageFavouritesButton = ({ popupId }) => {
 
       if (error) {
         console.error(error)
-        return setStatus("rejected")
+        setStatus("rejected")
+        return
```
Comment (camelPhonso) [inline src/components/popup-components/ManageFavouritesButton/ManageFavouritesButton.tsx:41]: No real comments, but I'm curious why we're explicitly opting to move the return to a new line.

Is this just a personal preference or hoping to follow any particular convention or something?

**Review by camelPhonso — APPROVED** [review]
Looking good! No real notes 👌
